application:
  name: meeching

spring:
  profiles: default
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
  datasource:
    platform: mysql
    #    initializationMode: always
    initializationMode: never
    #    data: classpath:data-mariadb.sql
    #    schema: classpath:schema-mariadb.sql
    hikari:
      pool-name: hikariPool01
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/meeching_dev
      user-name: meeching_admin
      password: 1234

  session:
    store-type: redis
    redis:
      flush-mode: on-save
      namespace: spring:session

  redis:
    host: localhost
    password: 1234
    port: 6379
    timetolive: 180 # value second
  jpa: #JPA Configuration
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.web: DEBUG
    com.skt.poc.common: DEBUG
    com.skt.poc.biz.component: DEBUG


poc:
  #  swagger:
  #    paths: /v1/** # PathSelectors.ant
  storage:
    location: C:\uploadFile
