
application:
  name: meeching

spring:
  profiles: default
  main:
    allow-bean-definition-overriding: true
  devtools:
    livereload:
      enabled: true
  datasource:
    platform: h2
    #    initializationMode: always
    initializationMode: never
#    data: classpath:data-mariadb.sql
#    schema: classpath:schema-mariadb.sql
    hikari:
      pool-name: hikariPool01
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:meeching_local;DB_CLOSE_DELAY=-1;MODE=MySQL
      user-name: sa
      password:

#  session:
#    store-type: redis
#    redis:
#      flush-mode: on-save
#      namespace: spring:session

  redis:
    host: poc-dev.redis.cache.windows.net
    password: iafM3+Td7nKhEYzNvlFDwZ3QcK4k0befAKwfrDvec50=
    port: 6379
    timetolive: 180 # value second
  jpa: #JPA Configuration
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG
    org.springframework.web: DEBUG


poc:
  #  swagger:
  #    paths: /v1/** # PathSelectors.ant
  storage:
    location: C:\uploadFile

server:
  port: 8080





